matrix:
  include:
    - os: osx
      language: objective-c
      osx_image: xcode8.3
      script:
        - set -o pipefail
        - xcodebuild -scheme AbstractionKitTests -configuration Release test -destination 'name=iPhone 7' | xcpretty -c